name: Build MacOS
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install meson gtk4
      - name: Build
        run: |
          meson setup builddir
          unzip assets/tasks.zip -d assets/
          meson compile -C builddir