name: Build
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install meson libgtk-4-dev unzip
      - name: Create subprojects
        run: |
          mkdir subprojects
          meson wrap install curl
          meson wrap install nlohmann_json
          meson wrap install sqlite3
      - name: Build
        run: |
          meson setup builddir
          unzip assets/tasks.zip -d assets/
          meson compile -C builddir
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install meson gtk4
      - name: Create subprojects
        run: |
          mkdir subprojects
          meson wrap install curl
          meson wrap install nlohmann_json
          meson wrap install sqlite3
      - name: Build
        run: |
          meson setup builddir
          unzip assets/tasks.zip -d assets/
          meson compile -C builddir
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            unzip
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-python3
            mingw-w64-ucrt-x86_64-gtk4
            mingw-w64-ucrt-x86_64-toolchain
            base-devel
            mingw-w64-ucrt-x86_64-meson
      - name: Create subprojects
        run: |
          mkdir subprojects
          meson wrap install curl --allow-insecure
          meson wrap install nlohmann_json --allow-insecure
          meson wrap install sqlite3 --allow-insecure
      - name: Build
        run: |
          meson setup builddir
          unzip assets/tasks.zip -d assets/
          meson compile -C builddir
          